#!/usr/bin/env python3
"""sync-helix-lsp.py — port helix-editor's languages.toml to artui's
flat `[server.<id>]` schema.

Helix declares language servers in `[language-server.<id>]` tables and binds
them to languages via `[[language]]` entries that name `language-servers =
["id", ...]`. We flatten that into one record per server, populating
`file_types` and `root_markers` from the union of every `[[language]]` that
references the server.

The output goes to `src/lsp/defaults.toml`. Re-running the script against
the same upstream commit must produce a byte-identical file — important for
audit / review (the workflow:`scripts/sync-helix-lsp.py && git diff
src/lsp/defaults.toml` should be empty unless upstream actually changed).

Usage:
  scripts/sync-helix-lsp.py                     # fetch master from GitHub
  scripts/sync-helix-lsp.py path/to/local.toml  # use a local copy
"""

from __future__ import annotations

import json
import sys
import urllib.request
from collections import OrderedDict, defaultdict
from pathlib import Path

# Vendored to keep the script dep-free; tomllib is stdlib on Python 3.11+.
try:
    import tomllib
except ImportError as exc:  # pragma: no cover
    sys.stderr.write("Python 3.11+ required (need stdlib `tomllib`)\n")
    raise SystemExit(1) from exc

UPSTREAM_URL = "https://raw.githubusercontent.com/helix-editor/helix/master/languages.toml"

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULTS_OUT = REPO_ROOT / "src" / "lsp" / "defaults.toml"

# Curated additions — servers helix defines but doesn't bind to a language by
# default (because helix prefers a different server for that language). These
# extensions/markers come from the upstream project's documentation, not
# guesswork. Re-validate when bumping helix.
EXTRA_BINDINGS: dict[str, dict[str, list[str]]] = {
    "pyright": {
        "file_types": ["py", "pyi"],
        "root_markers": ["pyrightconfig.json", "pyproject.toml", "setup.py"],
    },
    "basedpyright": {
        "file_types": ["py", "pyi"],
        "root_markers": ["pyrightconfig.json", "pyproject.toml", "setup.py"],
    },
    "pylyzer": {
        "file_types": ["py", "pyi"],
        "root_markers": ["pyproject.toml", "setup.py"],
    },
    "pyrefly": {
        "file_types": ["py", "pyi"],
        "root_markers": ["pyproject.toml", "pyrefly.toml"],
    },
    "deno": {
        "file_types": ["ts", "tsx", "js", "jsx", "mts", "mjs"],
        "root_markers": ["deno.json", "deno.jsonc", "import_map.json"],
    },
    # ruff is a linter that exposes an LSP; helix uses it as a secondary
    # server for python. Bundling here so users can switch it on.
    "ruff": {
        "file_types": ["py", "pyi"],
        "root_markers": ["pyproject.toml", "ruff.toml", ".ruff.toml"],
    },
}

HEADER = """\
# defaults.toml — vendored language-server registry.
#
# Generated by `scripts/sync-helix-lsp.py` from helix-editor/helix's
# `languages.toml` (MPL-2.0). Do not edit by hand — re-run the script.
# Attribution: see `src/lsp/NOTICE`.
#
# Schema: one `[server.<id>]` table per language server. `file_types` and
# `root_markers` are the union of every helix `[[language]]` that
# references the server.
"""


def fetch_helix_languages_toml(source: str | None) -> str:
    """Read upstream languages.toml from the given local path, or fetch
    over HTTPS when no path is given."""
    if source:
        return Path(source).read_text(encoding="utf-8")
    req = urllib.request.Request(
        UPSTREAM_URL,
        headers={"User-Agent": "artui-sync-helix-lsp"},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def index_languages(data: dict) -> dict:
    """Return `{server_id: {"file_types": set, "root_markers": list}}` from
    helix's `[[language]]` array."""
    by_server: dict[str, dict[str, set | list]] = defaultdict(
        lambda: {"file_types": set(), "root_markers": []}
    )
    for lang in data.get("language", []):
        servers = lang.get("language-servers", [])
        # `language-servers` entries can be plain strings or inline tables
        # like `{ name = "rust-analyzer", except-features = [...] }`. We
        # only need the name.
        names = []
        for entry in servers:
            if isinstance(entry, str):
                names.append(entry)
            elif isinstance(entry, dict):
                name = entry.get("name")
                if name:
                    names.append(name)
        for name in names:
            for ext in lang.get("file-types", []):
                if isinstance(ext, str):
                    by_server[name]["file_types"].add(ext.lstrip("."))
                elif isinstance(ext, dict):
                    glob = ext.get("glob")
                    if glob and "*" in glob:
                        suffix = glob.rsplit(".", 1)[-1]
                        if suffix and "/" not in suffix:
                            by_server[name]["file_types"].add(suffix)
            for marker in lang.get("roots", []):
                if marker not in by_server[name]["root_markers"]:
                    by_server[name]["root_markers"].append(marker)
    return by_server


def build_server_entries(data: dict) -> "OrderedDict[str, dict]":
    """Build the final `{id -> spec}` map sorted alphabetically by id so the
    output is reproducible."""
    indexed = index_languages(data)
    raw = data.get("language-server", {})

    # Apply curated extras — these don't override helix-derived bindings,
    # they only fill gaps for servers helix doesn't bind by default.
    for server_id, extras in EXTRA_BINDINGS.items():
        info = indexed[server_id]  # defaultdict creates if missing
        for ext in extras.get("file_types", []):
            info["file_types"].add(ext)
        for marker in extras.get("root_markers", []):
            if marker not in info["root_markers"]:
                info["root_markers"].append(marker)

    out: OrderedDict[str, dict] = OrderedDict()
    for server_id in sorted(raw.keys()):
        helix_spec = raw[server_id]
        command = helix_spec.get("command")
        if not command:
            # helix sometimes lists a server placeholder without a
            # command (e.g. for documentation only). Skip — we can't
            # spawn it.
            continue

        info = indexed.get(server_id, {"file_types": set(), "root_markers": []})

        spec: dict = {"command": command}
        args = helix_spec.get("args")
        if args:
            spec["args"] = list(args)

        file_types = sorted(info["file_types"])
        if file_types:
            spec["file_types"] = file_types

        root_markers = list(info["root_markers"])
        if root_markers:
            spec["root_markers"] = root_markers

        # `config` in helix maps to LSP `initializationOptions`.
        init_options = helix_spec.get("config")
        if init_options:
            spec["init_options"] = init_options

        env = helix_spec.get("environment")
        if env:
            spec["env"] = dict(env)

        out[server_id] = spec
    return out


def emit_toml(servers: "OrderedDict[str, dict]") -> str:
    """Hand-emit a deterministic TOML document. We avoid tomli_w / toml
    libraries to keep the script dep-free and to control formatting
    precisely.
    """
    chunks: list[str] = [HEADER]
    for server_id, spec in servers.items():
        # Quote ids with special TOML chars; everything else stays bare.
        if server_id.replace("-", "").replace("_", "").replace(".", "").isalnum():
            header = f"[server.{server_id}]"
        else:
            header = f'[server."{server_id}"]'
        chunks.append("")
        chunks.append(header)
        chunks.append(f"command = {toml_value(spec['command'])}")
        if "args" in spec:
            chunks.append(f"args = {toml_value(spec['args'])}")
        if "file_types" in spec:
            chunks.append(f"file_types = {toml_value(spec['file_types'])}")
        if "root_markers" in spec:
            chunks.append(f"root_markers = {toml_value(spec['root_markers'])}")
        if "init_options" in spec:
            # Inline-table form would be unwieldy for nested configs; emit
            # JSON inside a multi-line literal that we re-parse via serde
            # when reading. We round-trip via `init_options = """{...}"""`.
            chunks.append(
                "init_options_json = "
                + toml_value(json.dumps(spec["init_options"], sort_keys=True))
            )
        if "env" in spec:
            chunks.append("[server.{0}.env]".format(server_id))
            for k in sorted(spec["env"]):
                chunks.append(f"{toml_key(k)} = {toml_value(spec['env'][k])}")
    chunks.append("")
    return "\n".join(chunks)


def toml_key(k: str) -> str:
    if k.replace("_", "").replace("-", "").isalnum():
        return k
    return json.dumps(k)


def toml_value(v) -> str:
    if isinstance(v, str):
        # TOML basic strings allow literal unicode; only escape control
        # chars, backslash, and the closing double quote. JSON escapes
        # use surrogate pairs (`🔥`) which TOML rejects, so we
        # emit the codepoint directly.
        out = ['"']
        for ch in v:
            cp = ord(ch)
            if ch == "\\":
                out.append("\\\\")
            elif ch == '"':
                out.append('\\"')
            elif ch == "\n":
                out.append("\\n")
            elif ch == "\r":
                out.append("\\r")
            elif ch == "\t":
                out.append("\\t")
            elif cp < 0x20 or cp == 0x7F:
                out.append(f"\\u{cp:04X}")
            else:
                out.append(ch)
        out.append('"')
        return "".join(out)
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, list):
        return "[" + ", ".join(toml_value(x) for x in v) + "]"
    if isinstance(v, (int, float)):
        return repr(v)
    raise TypeError(f"unsupported toml value type: {type(v)!r}")


def main(argv: list[str]) -> int:
    source = argv[1] if len(argv) > 1 else None
    raw = fetch_helix_languages_toml(source)
    data = tomllib.loads(raw)
    servers = build_server_entries(data)
    output = emit_toml(servers)
    DEFAULTS_OUT.parent.mkdir(parents=True, exist_ok=True)
    DEFAULTS_OUT.write_text(output, encoding="utf-8")
    sys.stdout.write(
        f"Wrote {len(servers)} server entries to {DEFAULTS_OUT.relative_to(REPO_ROOT)}\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
